/* Solved
 * SRM 578 Div1 Easy
 * Author: Andy Y.F. Huang
 */
#include <algorithm>
#include <bitset>
#include <cassert>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <complex>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <valarray>
#include <vector>

#ifdef AZN
#include "Azn.cpp"
#endif

using namespace std;

template <int MOD> struct Uint32Mod {
  int val;

  Uint32Mod() : val(0) { }

  Uint32Mod(long long x) : val(x % MOD) {
    if (val < 0) val += MOD;
  }

  Uint32Mod& operator+=(const Uint32Mod & x) {
    val += x.val;
    if (val >= MOD) val -= MOD;
    return *this;
  }

  Uint32Mod operator+(const Uint32Mod & x) const {
    Uint32Mod res(*this);
    return res += x;
  }

  Uint32Mod& operator-=(const Uint32Mod & x) {
    val -= x.val;
    if (val < 0) val += MOD;
    return *this;
  }

  Uint32Mod operator-(const Uint32Mod & x) const {
    Uint32Mod res(*this);
    return res -= x;
  }

  Uint32Mod& operator*=(const Uint32Mod & x) {
    val = (long long) (val) * x.val % MOD;
    return *this;
  }

  Uint32Mod operator*(const Uint32Mod & x) const {
    Uint32Mod res(*this);
    return res *= x;
  }

  Uint32Mod& operator/=(const Uint32Mod & x) {
    return *this *= x.inv();
  }

  Uint32Mod operator/(const Uint32Mod & x)  const {
    Uint32Mod res(*this);
    return res /= x;
  }

  Uint32Mod power(long long expon) const {
    Uint32Mod ans, temp(*this);
    ans.val = 1;
    for (; expon > 0; expon >>= 1) {
      if (expon & 1) ans *= temp;
      temp *= temp;
    }
    return ans;
  }

  Uint32Mod inv() const {
    return power(MOD - 2);
  }

  friend ostream& operator<<(ostream& out, Uint32Mod & x) {
    return out << x.val;
  }

} ;

struct GooseInZooDivOne {
  int count(vector <string> field, int dist);
} ;

#define MOD 1000000007
typedef Uint32Mod<MOD> Int;
typedef pair<int, int> Bird;
Int fact[2555], invfact[2555], two[2555];
vector<Bird> birds;
vector<int> adj[2555];

Int comb(int n, int k) {
  return fact[n] * invfact[k] * invfact[n - k];
}

int GooseInZooDivOne::count(vector <string> field, int dist) {
  fact[0] = invfact[0] = two[0] = 1;
  for (int i = 1; i <= 2550; i++) {
    fact[i] = fact[i - 1] * i;
    invfact[i] = fact[i].inv();
    two[i] = two[i - 1] + two[i - 1];
  }
  birds.clear();
  int rows = field.size(), cols = field[0].size();
  for (int r = 0; r < rows; r++)
    for (int c = 0; c < cols; c++)
      if (field[r][c] == 'v')
        birds.push_back(Bird(r, c));
  int size = birds.size();
  for (int i = 0; i < size; i++) {
    adj[i].clear();
    for (int j = 0; j < size; j++)
      if (abs(birds[i].first - birds[j].first) + abs(birds[i].second - birds[j].second) <= dist)
        adj[i].push_back(j);
  }
  static bool vis[2555];
  memset(vis, false, sizeof (vis));
  queue<int> q;
  int odd = 0, even = 0, cnt = 0;
  for (int i = 0; i < size; i++) {
    if (vis[i]) continue;
    q.push(i);
    vis[i] = true;
    int temp = 0;
    for (int at; !q.empty(); q.pop()) {
      temp++;
      at = q.front();
      for (int i = 0; i < (int) adj[at].size(); i++)
        if (!vis[adj[at][i]]) {
          vis[adj[at][i]] = true;
          q.push(adj[at][i]);
        }
    }
    cnt += temp;
    temp %= 2;
    if (temp == 0) even++;
    else odd++;
  }
  //pln(odd, even);
  Int res = 0;
  for (int i = 2; i <= odd; i += 2)
    res += two[even] * comb(odd, i);
  if (even > 0)
    res += two[even] - 1;
  return res.val;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof

bool KawigiEdit_RunTest(int testNum, vector <string> p0, int p1, bool hasAnswer, int p2) {
  cout << "Test " << testNum << ": [" << "{";
  for (int i = 0; int(p0.size()) > i; ++i) {
    if (i > 0) {
      cout << ",";
    }
    cout << "\"" << p0[i] << "\"";
  }
  cout << "}" << "," << p1;
  cout << "]" << endl;
  GooseInZooDivOne *obj;
  int answer;
  obj = new GooseInZooDivOne();
  clock_t startTime = clock();
  answer = obj->count(p0, p1);
  clock_t endTime = clock();
  delete obj;
  bool res;
  res = true;
  cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
  if (hasAnswer) {
    cout << "Desired answer:" << endl;
    cout << "\t" << p2 << endl;
  }
  cout << "Your answer:" << endl;
  cout << "\t" << answer << endl;
  if (hasAnswer) {
    res = answer == p2;
  }
  if (!res) {
    cout << "DOESN'T MATCH!!!!" << endl;
  }
  else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
    cout << "FAIL the timeout" << endl;
    res = false;
  }
  else if (hasAnswer) {
    cout << "Match :-)" << endl;
  }
  else {
    cout << "OK, but is it right?" << endl;
  }
  cout << "" << endl;
  return res;
}

int main() {
  #ifdef AZN
  freopen("output.txt", "w", stdout);
  freopen("azn.txt", "w", stderr);
  #endif

  bool all_right;
  all_right = true;

  vector <string> p0;
  int p1;
  int p2;

  {
    // ----- test 0 -----
    string t0[] = {"vvv"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 0;
    p2 = 3;
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 1 -----
    string t0[] = {"."};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 100;
    p2 = 0;
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 2 -----
    string t0[] = {"vvv"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 1;
    p2 = 0;
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 3 -----
    string t0[] = {"v.v..................v............................", ".v......v..................v.....................v", "..v.....v....v.........v...............v......v...", ".........vvv...vv.v.........v.v..................v", ".....v..........v......v..v...v.......v...........", "...................vv...............v.v..v.v..v...", ".v.vv.................v..............v............", "..vv.......v...vv.v............vv.....v.....v.....", "....v..........v....v........v.......v.v.v........", ".v.......v.............v.v..........vv......v.....", "....v.v.......v........v.....v.................v..", "....v..v..v.v..............v.v.v....v..........v..", "..........v...v...................v..............v", "..v........v..........................v....v..v...", "....................v..v.........vv........v......", "..v......v...............................v.v......", "..v.v..............v........v...............vv.vv.", "...vv......v...............v.v..............v.....", "............................v..v.............."
                   "...v", ".v.............v.......v..........................", "......v...v........................v..............", ".........v.....v..............vv..................", "................v..v..v.........v....v.......v....", "........v.....v.............v......v.v............", "...........v....................v.v....v.v.v...v..", "...........v......................v...v...........", "..........vv...........v.v.....................v..", ".....................v......v............v...v....", ".....vv..........................vv.v.....v.v.....", ".vv.......v...............v.......v..v.....v......", "............v................v..........v....v....", "................vv...v............................", "................v...........v........v...v....v...", "..v...v...v.............v...v........v....v..v....", "......v..v.......v........v..v....vv..............", "...........v..........v........v.v................", "v.v......v................v....................v..", ".v........v............................."
                   "...v......", "............................v...v.......v.........", "........................vv.v..............v...vv..", ".......................vv........v.............v..", "...v.............v.........................v......", "....v......vv...........................v.........", "....vv....v................v...vv..............v..", "..................................................", "vv........v...v..v.....v..v..................v....", ".........v..............v.vv.v.............v......", ".......v.....v......v...............v.............", "..v..................v................v....v......", ".....v.....v.....................v.v......v......."};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 3;
    p2 = 898961330;
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------
  }

  if (all_right) {
    cout << "You're a stud (at least on the example cases)!" << endl;
  }
  else {
    cout << "Some of the test cases had errors." << endl;
  }
  return 0;
}
// PROBLEM STATEMENT
// Crow Keith is looking at the goose cage in the zoo.
// The bottom of the cage is divided into a grid of square cells.
// There are some birds sitting on those cells (with at most one bird per cell).
// Some of them are geese and all the others are ducks.
//
// Keith wants to know which birds are geese.
// He knows the following facts about them:
//
// There is at least one goose in the cage.
// The number of geese is even.
// Each bird within Manhattan distance dist of any goose is also a goose.
//
//
// You are given a vector <string> field and the int dist.
// The array field describes the bottom of the cage.
// Each character of each element of field describes one of the cells.
// The meaning of individual characters follows.
//
// The character 'v' represents a cell that contains a bird.
// The character '.' represents an empty cell.
//
//
// Return the number of possible sets of geese in the cage, modulo 1,000,000,007.
// Note that for some of the test cases there can be no possible sets of geese.
//
// DEFINITION
// Class:GooseInZooDivOne
// Method:count
// Parameters:vector <string>, int
// Returns:int
// Method signature:int count(vector <string> field, int dist)
//
//
// NOTES
// -The Manhattan distance between cells (a,b) and (c,d) is |a-c| + |b-d|, where || denotes absolute value. In words, the Manhattan distance is the smallest number of steps needed to get from one cell to the other, given that in each step you can move to a cell that shares a side with your current cell.
//
//
// CONSTRAINTS
// -field will contain between 1 and 50 elements, inclusive.
// -Each element of field will contain between 1 and 50 characters, inclusive.
// -Each element of field will contain the same number of characters.
// -Each character of each element of field will be 'v' or '.'.
// -dist will be between 0 and 100, inclusive.
//
//
// EXAMPLES
//
// 0)
// {"vvv"}
// 0
//
// Returns: 3
//
// There are three possible sets of positions of geese: "ggd", "gdg", or "dgg" ('g' are geese and 'd' are ducks).
//
// 1)
// {"."}
// 100
//
// Returns: 0
//
// The number of geese must be positive, but there are no birds in the cage.
//
// 2)
// {"vvv"}
// 1
//
// Returns: 0
//
//
//
// 3)
// {"v.v..................v............................"
// ,".v......v..................v.....................v"
// ,"..v.....v....v.........v...............v......v..."
// ,".........vvv...vv.v.........v.v..................v"
// ,".....v..........v......v..v...v.......v..........."
// ,"...................vv...............v.v..v.v..v..."
// ,".v.vv.................v..............v............"
// ,"..vv.......v...vv.v............vv.....v.....v....."
// ,"....v..........v....v........v.......v.v.v........"
// ,".v.......v.............v.v..........vv......v....."
// ,"....v.v.......v........v.....v.................v.."
// ,"....v..v..v.v..............v.v.v....v..........v.."
// ,"..........v...v...................v..............v"
// ,"..v........v..........................v....v..v..."
// ,"....................v..v.........vv........v......"
// ,"..v......v...............................v.v......"
// ,"..v.v..............v........v...............vv.vv."
// ,"...vv......v...............v.v..............v....."
// ,"............................v..v.................v"
// ,".v.............v.......v.........................."
// ,"......v...v........................v.............."
// ,".........v.....v..............vv.................."
// ,"................v..v..v.........v....v.......v...."
// ,"........v.....v.............v......v.v............"
// ,"...........v....................v.v....v.v.v...v.."
// ,"...........v......................v...v..........."
// ,"..........vv...........v.v.....................v.."
// ,".....................v......v............v...v...."
// ,".....vv..........................vv.v.....v.v....."
// ,".vv.......v...............v.......v..v.....v......"
// ,"............v................v..........v....v...."
// ,"................vv...v............................"
// ,"................v...........v........v...v....v..."
// ,"..v...v...v.............v...v........v....v..v...."
// ,"......v..v.......v........v..v....vv.............."
// ,"...........v..........v........v.v................"
// ,"v.v......v................v....................v.."
// ,".v........v................................v......"
// ,"............................v...v.......v........."
// ,"........................vv.v..............v...vv.."
// ,".......................vv........v.............v.."
// ,"...v.............v.........................v......"
// ,"....v......vv...........................v........."
// ,"....vv....v................v...vv..............v.."
// ,".................................................."
// ,"vv........v...v..v.....v..v..................v...."
// ,".........v..............v.vv.v.............v......"
// ,".......v.....v......v...............v............."
// ,"..v..................v................v....v......"
// ,".....v.....v.....................v.v......v......."}
// 3
//
// Returns: 898961330
//
//
//
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
