/* Solved
 * SRM 579 Div2 Hard
 * Author: Andy Y.F. Huang
 */
#include <algorithm>
#include <bitset>
#include <cassert>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <complex>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <valarray>
#include <vector>

#ifdef AZN
#include "Azn.cpp"
#endif

using namespace std;

struct MarblePositioning {
	double totalWidth(vector <int> rad);
};

long double x[11], y[11];

long double dist(long double x, long double y) {
  return x * x + y * y;
}

long long sq(int x) {
  return 1LL * x * x;
}

double MarblePositioning::totalWidth(vector <int> rad) {
  int len = rad.size();
  sort(rad.begin(), rad.end());
  long double ans = 1e18;
  //int sum = 2 * accumulate(rad.begin(), rad.end(), 0);
  do {
    memset(x, 0, sizeof (x));
    y[0] = rad[0];
    for (int i = 1; i < len; i++)
      for (int j = 0; j < i; j++)
        x[i] = max(x[i], x[j] + sqrt(4LL * rad[i] * rad[j]));
    ans = min(ans, x[len - 1]);
  } while (next_permutation(rad.begin(), rad.end()));
  //pln(setprecision(15), ans);
  return (double )ans;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <int> p0, bool hasAnswer, double p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}";
	cout << "]" << endl;
	MarblePositioning *obj;
	double answer;
	obj = new MarblePositioning();
	clock_t startTime = clock();
	answer = obj->totalWidth(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == answer && fabs(p1 - answer) <= 1e-9 * max(1.0, fabs(p1));
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
#ifdef AZN
freopen("output.txt", "w", stdout);
freopen("azn.txt", "w", stderr);
#endif

	bool all_right;
	all_right = true;

	vector <int> p0;
	double p1;

	{
	// ----- test 0 -----
	int t0[] = {1,2};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 2.8284271247461903;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	int t0[] = {7,7,7};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 28.0;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	int t0[] = {10,20,30};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 62.92528739883945;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	int t0[] = {100,100,11,11,25};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 200.0;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	int t0[] = {1,999950884,1};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 63246.0;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// NOTE: This problem statement contains images that may not display properly if viewed outside of the applet.
//
//
// Everybody loves geometry, so here is a geometry problem.
// You have a few marbles of possibly different sizes.
// You are given a vector <int> radius that describes the marbles: each element of radius is the radius of one of your marbles.
//
// You want to place all marbles onto a straight line that is drawn on the table.
// Clearly, this makes the problem two-dimensional: we can just view the marbles as circles that will all be touching the line from above.
// Of course, the marbles cannot overlap, so in our problem no two circles are allowed to overlap.
// Note that you may place the marbles onto the line in any order, you do not have to preserve the order in which they are given in radius.
//
// Additionally, you want to pack the bottoms of the marbles as close together as possible.
// More precisely:
// For each marble consider the point where it touches the line.
// Compute and return the smallest possible distance between the farthest two of those points.
// (That is, if you imagine the line as going from the left to the right, your task is to minimize the distance between the leftmost and the rightmost of the points where the circles touch the line.)
//
// DEFINITION
// Class:MarblePositioning
// Method:totalWidth
// Parameters:vector <int>
// Returns:double
// Method signature:double totalWidth(vector <int> radius)
//
//
// NOTES
// -The returned values must have an absolute or relative error less than 1e-9.
//
//
// CONSTRAINTS
// -radius will contain between 2 and 8 elements, inclusive.
// -Each element of radius will be between 1 and 1000000000 (10^9), inclusive.
//
//
// EXAMPLES
//
// 0)
// {1, 2}
//
// Returns: 2.8284271247461903
//
// One of the best ways to place the marbles is the following one:
//
//
//
//
// 1)
// {7,7,7}
//
// Returns: 28.0
//
//
//
// 2)
// {10, 20, 30}
//
// Returns: 62.92528739883945
//
//
//
//
//
// 3)
// {100, 100,11,11,25}
//
// Returns: 200.0
//
//
//
// 4)
// {1,999950884,1}
//
// Returns: 63246.0
//
//
//
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
