/*
 * Solved
 * SRM 572 Div1 Easy
 * Author: Andy Y.F. Huang
 */
#include <algorithm>
#include <bitset>
#include <cassert>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <complex>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <valarray>
#include <vector>

#ifdef AZN
#include "Azn.cpp"
#endif

using namespace std;

struct NewArenaPassword {
  int minChange(string oldPassword, int K);
} ;

template <size_t MAXSIZE> struct DisjointSet {
  int tree[MAXSIZE];

  void makeset() {
    memset(tree, 0xFF, sizeof (tree));
  }

  void unite(int a, int b) {
    int root1 = find(a), root2 = find(b);
    if (root1 == root2) return;
    if (tree[root1] > tree[root2]) tree[root1] = root2;
    else {
      if (tree[root1] == tree[root2]) tree[root1]--;
      tree[root2] = root1;
    }
  }

  int find(int node) {
    return tree[node] < 0 ? node : (tree[node] = find(tree[node]));
  }
} ;

int NewArenaPassword::minChange(string old, int K) {
  DisjointSet<55> dsu;
  dsu.makeset();
  int len = old.length();
  for (int i = 0; i < K; i++)
    dsu.unite(i, len - K + i);
  int ans = 0;
  for (int i = 0; i < len; i++) {
    if (dsu.find(i) != i) continue;
    vector<char> vals;
    for (int j = 0; j < len; j++)
      if (dsu.find(j) == i)
        vals.push_back(old[j]);
    sort(vals.begin(), vals.end());
    int best = 0;
    for (int j = 0; j < (int) vals.size(); j++)
      best = max(best, count(vals.begin(), vals.end(), vals[j]));
    ans += vals.size() - best;
  }
  return ans;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof

bool KawigiEdit_RunTest(int testNum, string p0, int p1, bool hasAnswer, int p2) {
  cout << "Test " << testNum << ": [" << "\"" << p0 << "\"" << "," << p1;
  cout << "]" << endl;
  NewArenaPassword *obj;
  int answer;
  obj = new NewArenaPassword();
  clock_t startTime = clock();
  answer = obj->minChange(p0, p1);
  clock_t endTime = clock();
  delete obj;
  bool res;
  res = true;
  cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
  if (hasAnswer) {
    cout << "Desired answer:" << endl;
    cout << "\t" << p2 << endl;
  }
  cout << "Your answer:" << endl;
  cout << "\t" << answer << endl;
  if (hasAnswer) {
    res = answer == p2;
  }
  if (!res) {
    cout << "DOESN'T MATCH!!!!" << endl;
  }
  else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
    cout << "FAIL the timeout" << endl;
    res = false;
  }
  else if (hasAnswer) {
    cout << "Match :-)" << endl;
  }
  else {
    cout << "OK, but is it right?" << endl;
  }
  cout << "" << endl;
  return res;
}

int main() {
  #ifdef AZN
  freopen("output.txt", "w", stdout);
  freopen("azn.txt", "w", stderr);
  #endif

  bool all_right;
  all_right = true;

  string p0;
  int p1;
  int p2;

  {
    // ----- test 0 -----
    p0 = "topcoderopen";
    p1 = 5;
    p2 = 3;
    all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 1 -----
    p0 = "puyopuyo";
    p1 = 4;
    p2 = 0;
    all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 2 -----
    p0 = "loool";
    p1 = 3;
    p2 = 1;
    all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 3 -----
    p0 = "arena";
    p1 = 5;
    p2 = 0;
    all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
    // ------------------
  }

  {
    // ----- test 4 -----
    p0 = "amavckdkz";
    p1 = 7;
    p2 = 5;
    all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
    // ------------------
  }

  if (all_right) {
    cout << "You're a stud (at least on the example cases)!" << endl;
  }
  else {
    cout << "Some of the test cases had errors." << endl;
  }
  return 0;
}
// PROBLEM STATEMENT
// You are a huge fan of an online programming contest called SRM (Special Round Match). To participate in an SRM contest, you must first download an applet called Arena, log in to the Arena by entering your username and password, and start competing.
//
// Recently, to avoid hackers' attacks on the Arena, SRM imposes a new rule for the users' passwords. From now on, the first K characters of each user's password must match its last K characters. In this way, if someone enters a password with different first and last K characters repeatedly, it can be considered an attack from hackers.
//
// However, you love your old password and do not want to change many characters from it. You are given a string oldPassword representing your old password, and an int K. Return the minimum number of characters of oldPassword that must be changed so that the string containing the first K characters of oldPassword is equal to the string containing the last K characters of oldPassword.
//
// DEFINITION
// Class:NewArenaPassword
// Method:minChange
// Parameters:string, int
// Returns:int
// Method signature:int minChange(string oldPassword, int K)
//
//
// CONSTRAINTS
// -oldPassword will contain between 1 and 50 characters, inclusive.
// -Each character of oldPassword will be a lowercase letter 'a' - 'z'.
// -K will be between 1 and the number of characters of oldPassword, inclusive.
//
//
// EXAMPLES
//
// 0)
// "topcoderopen"
// 5
//
// Returns: 3
//
// A possible solution is changing your password into "topcndetopcn". To do this, you must change the 4th, 7th, and 10th characters (0-based) of "topcoderopen".
//
// 1)
// "puyopuyo"
// 4
//
// Returns: 0
//
// Your old password already satisfies the new rule.
//
// 2)
// "loool"
// 3
//
// Returns: 1
//
// The first and the last K characters can overlap. In this case, the only optimal solution is to change your password into "lolol".
//
// 3)
// "arena"
// 5
//
// Returns: 0
//
//
//
// 4)
// "amavckdkz"
// 7
//
// Returns: 5
//
//
//
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
