/* Solved
 * SRM 579 Div2 Medium
 * Author: Andy Y.F. Huang
 */
#include <algorithm>
#include <bitset>
#include <cassert>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <complex>
#include <deque>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <valarray>
#include <vector>

#ifdef AZN
#include "Azn.cpp"
#endif

using namespace std;

struct UndoHistory {
  int minPresses(vector <string> lines);
} ;

int lcp(string a, string b) {
  for (int i = 0; i < (int) a.size() && i < (int) b.size(); i++)
    if (a[i] != b[i])
      return i;
  return min(a.size(), b.size());
}

int UndoHistory::minPresses(vector <string> lines) {
  int res = lines[0].size(), len = lines.size();
  for (int i = 1; i < len; i++) {
    unsigned best = 1111u;
    if (lcp(lines[i], lines[i - 1]) == (int) lines[i - 1].size())
      best = min(best, lines[i].size() - lines[i - 1].size());
    int l = 0;
    for (int j = 0; j < i; j++)
      l = max(l, lcp(lines[j], lines[i]));
    best = min(best, 2 + lines[i].size() - l);
    res += best;
  }
  return res + len;
}


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof

bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
  cout << "Test " << testNum << ": [" << "{";
  for (int i = 0; int(p0.size()) > i; ++i) {
    if (i > 0) {
      cout << ",";
    }
    cout << "\"" << p0[i] << "\"";
  }
  cout << "}";
  cout << "]" << endl;
  UndoHistory *obj;
  int answer;
  obj = new UndoHistory();
  clock_t startTime = clock();
  answer = obj->minPresses(p0);
  clock_t endTime = clock();
  delete obj;
  bool res;
  res = true;
  cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
  if (hasAnswer) {
    cout << "Desired answer:" << endl;
    cout << "\t" << p1 << endl;
  }
  cout << "Your answer:" << endl;
  cout << "\t" << answer << endl;
  if (hasAnswer) {
    res = answer == p1;
  }
  if (!res) {
    cout << "DOESN'T MATCH!!!!" << endl;
  }
  else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
    cout << "FAIL the timeout" << endl;
    res = false;
  }
  else if (hasAnswer) {
    cout << "Match :-)" << endl;
  }
  else {
    cout << "OK, but is it right?" << endl;
  }
  cout << "" << endl;
  return res;
}

int main() {
  #ifdef AZN
  freopen("output.txt", "w", stdout);
  freopen("azn.txt", "w", stderr);
  #endif

  bool all_right;
  all_right = true;

  vector <string> p0;
  int p1;

  {
    // ----- test 0 -----
    string t0[] = {"tomorrow", "topcoder"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 18;
    all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
    // ------------------
  }

  {
    // ----- test 1 -----
    string t0[] = {"a", "b"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 6;
    all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
    // ------------------
  }

  {
    // ----- test 2 -----
    string t0[] = {"a", "ab", "abac", "abacus"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 10;
    all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
    // ------------------
  }

  {
    // ----- test 3 -----
    string t0[] = {"pyramid", "sphinx", "sphere", "python", "serpent"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 39;
    all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
    // ------------------
  }

  {
    // ----- test 4 -----
    string t0[] = {"ba", "a", "a", "b", "ba"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 13;
    all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
    // ------------------
  }

  {
    // ----- test 5 -----
    string t0[] = {"absolutely", "abs", "absolute"};
    p0.assign(t0, t0 + sizeof (t0) / sizeof (t0[0]));
    p1 = 17;
    all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
    // ------------------
  }

  if (all_right) {
    cout << "You're a stud (at least on the example cases)!" << endl;
  }
  else {
    cout << "Some of the test cases had errors." << endl;
  }
  return 0;
}
// PROBLEM STATEMENT
// Bob is using a peculiar text editor to write a sequence of lines of text.
// The editor consists of three parts: a results window, a text buffer and an undo history.
// More details about the three parts follow.
//
// The results window contains a sequence of strings: the lines of text you already wrote. Initially, the results window is empty.
// The text buffer contains a string: the line you are writing at the moment. Initially, the string in the text buffer is empty.
// The undo history contains a sequence of strings: all the past states of the text buffer. Initially, the undo history contains a single element: an empty string.
//
//
// You are given a vector <string> lines.
// Bob would like to print the contents of lines into the results window.
// (At the end, the sequence of strings stored in the results window must be precisely equal to lines. Order of elements matters.)
// Additionally, Bob would like to do so as quickly as possible.
// He is able to take the following actions:
//
//
// Bob may type a lowercase letter. The letter is appended to the text buffer. The new text buffer is then added as a new element of the undo history. (For example, if the text buffer currently contains "do", then pressing 'g' changes the text buffer to "dog" and then stores "dog" into the undo history.)
// Bob may press Enter. When he does so, the current content of the text buffer is printed to the results window as a new line, after the lines that were printed earlier. The text buffer remains unmodified. (For example, if the text buffer contains "dog" and Bob presses Enter, "dog" will be appended to the results window, and the results buffer still contains "dog".)
// Bob may use two mouse clicks to restore any entry from the undo history to the text buffer. This operation does not modify the undo history.
//
//
// Return the minimum total number of button presses (keyboard and mouse) that Bob needs to print all the given lines into the results window.
//
// DEFINITION
// Class:UndoHistory
// Method:minPresses
// Parameters:vector <string>
// Returns:int
// Method signature:int minPresses(vector <string> lines)
//
//
// CONSTRAINTS
// -lines will contain between 1 and 50 elements, inclusive.
// -Each element of lines will contain between 1 and 50 characters, inclusive.
// -Each element of lines will contain only lowercase letters ('a'-'z').
//
//
// EXAMPLES
//
// 0)
// {"tomorrow", "topcoder"}
//
// Returns: 18
//
//
// Type 't'. The text buffer now contains "t", and the undo history now contains "" and "t".
// Type 'o'. The text buffer now contains "to", and the undo history now contains "", "t", and "to".
// Using six more keypresses, type the letters in "morrow". The text buffer now contains "tomorrow" and the undo history contains all prefixes of "tomorrow". The results window is still empty.
// Press Enter. The results window now contains one string: "tomorrow".
// Click the mouse twice to restore "to" from undo history.
// Using another six keypresses, type the letters in "pcoder".
// Press Enter. The results window now contains "tomorrow" and "topcoder", in this order, and we are done.
//
// The total number of button presses was 8 (typing "tomorrow") + 1 (Enter) + 2 (mouse) + 6 (typing "pcoder") + 1 (Enter) = 18.
//
// 1)
// {"a","b"}
//
// Returns: 6
//
// After typing "a" and pressing enter, we need to restore the empty string (which is always present at the top of the undo buffer) before typing "b".
//
// 2)
// {"a", "ab", "abac", "abacus" }
//
// Returns: 10
//
// There are times when it is not necessary to use the undo history at all.
//
// 3)
// {"pyramid", "sphinx", "sphere", "python", "serpent"}
//
// Returns: 39
//
//
//
// 4)
// {"ba","a","a","b","ba"}
//
//
// Returns: 13
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
